# Generated by Django 2.0.2 on 2018-05-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=80)),
                ('Pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
            ],
            options={
                'verbose_name': '评论信息',
                'verbose_name_plural': '评论信息',
            },
        ),
        migrations.CreateModel(
            name='FollowsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '用户关注关联信息',
                'verbose_name_plural': '用户关注关联信息',
            },
        ),
        migrations.CreateModel(
            name='LikesLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '点赞关联信息',
                'verbose_name_plural': '点赞关联信息',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/photos', verbose_name='图片')),
            ],
            options={
                'verbose_name': '相册图片信息',
                'verbose_name_plural': '相册图片信息',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(default='', max_length=150, verbose_name='动态')),
                ('Pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('likes_num', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('com_num', models.PositiveIntegerField(default=0, verbose_name='评论数')),
            ],
            options={
                'verbose_name': '动态信息',
                'verbose_name_plural': '动态信息',
            },
        ),
        migrations.CreateModel(
            name='PostsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '收藏关联信息',
                'verbose_name_plural': '收藏关联信息',
            },
        ),
        migrations.CreateModel(
            name='UsersActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, '注册'), (2, '忘记')], default=1, verbose_name='状态')),
                ('code', models.CharField(default='', max_length=10, verbose_name='验证码')),
            ],
            options={
                'verbose_name': '验证码信息',
                'verbose_name_plural': '验证码信息',
            },
        ),
    ]
