# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-08 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ins_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiApplicationer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appId', models.CharField(default='', max_length=20)),
                ('appKey', models.CharField(default='', max_length=100)),
                ('publicKey', models.CharField(default='', max_length=160)),
                ('privateKey', models.CharField(default='', max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='FollowsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from+', to=settings.AUTH_USER_MODEL, verbose_name='关注者')),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to=settings.AUTH_USER_MODEL, verbose_name='被关注者')),
            ],
        ),
    ]
