# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-08 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ins_api', '0002_apiapplicationer_followslink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiApplicationer',
            new_name='ApiApplication',
        ),
    ]
