# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-11 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins_api', '0002_auto_20180511_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersactive',
            name='hashkey',
            field=models.CharField(default='', max_length=100, verbose_name='哈希值'),
        ),
    ]
