# Generated by Django 2.0.2 on 2018-05-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins_api', '0002_auto_20180508_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='introduction',
            field=models.CharField(default='', max_length=150, verbose_name='动态描述'),
        ),
    ]
