# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-17 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import users.storage


class Migration(migrations.Migration):

    dependencies = [
        ('ins_api', '0002_auto_20180515_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='photo_0',
            field=models.ImageField(default='', storage=users.storage.ImageStorage(), upload_to='photos/', verbose_name='图片'),
        ),
    ]
