# Generated by Django 2.0.2 on 2018-05-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins_api', '0003_auto_20180509_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='introduction',
            field=models.TextField(default='', max_length=150, verbose_name='动态描述'),
        ),
    ]
