# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-08 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins_api', '0003_auto_20180508_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiApplicationer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=10)),
                ('permission', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='ApiApplication',
            new_name='ApiList',
        ),
    ]
