# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-24 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ins_api', '0003_posts_photo_0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Pub_time',
            new_name='time',
        ),
    ]
