# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-08 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins_api', '0004_auto_20180508_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilist',
            name='privateKey',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='apilist',
            name='publicKey',
            field=models.CharField(default='', max_length=180),
        ),
    ]
