# Generated by Django 2.0.2 on 2018-05-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins_api', '0004_auto_20180509_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersactive',
            name='code',
            field=models.CharField(default='保存后自动生成验证码', max_length=10, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='usersactive',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '注册'), (2, '忘记')], default=2, verbose_name='状态'),
        ),
    ]
