# Generated by Django 2.0.2 on 2018-05-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180509_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2000-01-01', verbose_name='生py日'),
        ),
    ]
